[package]
name = "tinyhttp-codegen"
version = "0.6.0"
authors = ["Mateo Cabanal <mateo200525@gmail.com>"]
edition = "2018"
license = "GPL-2.0-or-later"
keywords = ["http", "server"]
description = "Provides codegen for tinyhttp"
repository = "https://github.com/mateocabanal/tinyhttp-codegen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1.0.18"
tinyhttp-internal = { path = "../tinyhttp-internal", version = "0.6.0", default-features = false }
